### ISSUE TITLE
Extra exception detection boxes

### ISSUE THREAD

**Issue by qiansi** [STVIR/Grid-R-CNN#3]
when i train the model on my owner dataset， recall is very high but when i check the badcase , i find some extra exception detection boxes even on clean surface. What could be the cause?

**Comment by luxiin** [comment]
To suppress FP boxes, you could set a higher threshold or add another NMS process. We discard the output NMS process because running it on 80 categories(COCO) is slow. You can add it in other cases to achieve better performance.

**Comment by qiansi** [comment]
Thanks for reply, Perfectly solved our problem.👍
